name: Linter (SwiftLint)

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
      - '*'

jobs:
    runs-on: macos-latest
    
    name: swift-format-lint
    # You may pin to the exact commit or the version.
    # uses: Iron-Ham/swift-format-linter-action@2c8a693da54be38b8f0b6dfd94ac83e6fc91aa08
    uses: norio-nomura/action-swiftlint@3.2.1
